FUNCTION zdop_bte_tedarikci_kontrol.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_LFA1) LIKE  LFA1 STRUCTURE  LFA1
*"     VALUE(I_LFB1) LIKE  LFB1 STRUCTURE  LFB1
*"     VALUE(I_LFA1_OLD) LIKE  LFA1 STRUCTURE  LFA1
*"     VALUE(I_LFB1_OLD) LIKE  LFB1 STRUCTURE  LFB1
*"     VALUE(I_LFM1) LIKE  LFM1 STRUCTURE  LFM1
*"  TABLES
*"      T_XLFBK STRUCTURE  FLFBK
*"      T_YLFBK STRUCTURE  FLFBK
*"      T_XLFB5 STRUCTURE  FLFB5
*"      T_YLFB5 STRUCTURE  FLFB5
*"      T_XLFZA STRUCTURE  FLFZA
*"      T_YLFZA STRUCTURE  FLFZA
*"      T_XLFAS STRUCTURE  FLFAS OPTIONAL
*"      T_YLFAS STRUCTURE  FLFAS OPTIONAL
*"      T_XLFLR STRUCTURE  FLFLR OPTIONAL
*"      T_YLFLR STRUCTURE  FLFLR OPTIONAL
*"      T_XLFM2 STRUCTURE  FLFM2 OPTIONAL
*"      T_YLFM2 STRUCTURE  FLFM2 OPTIONAL
*"      T_XWYT1 STRUCTURE  FWYT1 OPTIONAL
*"      T_YWYT1 STRUCTURE  FWYT1 OPTIONAL
*"      T_XWYT1T STRUCTURE  FWYT1T OPTIONAL
*"      T_YWYT1T STRUCTURE  FWYT1T OPTIONAL
*"      T_XWYT3 STRUCTURE  FWYT3 OPTIONAL
*"      T_YWYT3 STRUCTURE  FWYT3 OPTIONAL
*"      T_XLFAT STRUCTURE  FLFAT OPTIONAL
*"      T_XLFBW STRUCTURE  FLFBW OPTIONAL
*"      T_YLFAT STRUCTURE  FLFAT OPTIONAL
*"      T_YLFBW STRUCTURE  FLFBW OPTIONAL
*"----------------------------------------------------------------------

  IF i_lfa1-land1 = 'DE'.
    MESSAGE 'ÜLKE DEĞERİ İÇİN ALMANYA KULLANILAMAZ' TYPE 'I'. " DISPLAY LIKE 'E'.
  ENDIF.

ENDFUNCTION.
